[package]
name = "borg_helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
hostname = "0.3.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.30"
